# Generated by Django 3.0 on 2019-12-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20191221_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='email_address', to='contacts.Person'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='phone_number', to='contacts.Person'),
        ),
    ]
