# Generated by Django 3.0 on 2019-12-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20191223_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Telefon'),
        ),
    ]
