# Generated by Django 3.0 on 2019-12-26 17:55

import contacts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20191223_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, validators=[contacts.validators.validate_first_name], verbose_name='Imie'),
        ),
    ]
